//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Data.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 无法执行该操作。ChangeTracker是null或ObjectState为这个操作是无效的 的本地化字符串。
        /// </summary>
        internal static string exception_ChangeTrackerIsNullOrStateIsNOK {
            get {
                return ResourceManager.GetString("exception_ChangeTrackerIsNullOrStateIsNOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container 容器不能空 的本地化字符串。
        /// </summary>
        internal static string exception_ContainerCannotBeNull {
            get {
                return ResourceManager.GetString("exception_ContainerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式是null或不是一个有效的函数表达式 的本地化字符串。
        /// </summary>
        internal static string exception_ExpressionPathNotValid {
            get {
                return ResourceManager.GetString("exception_ExpressionPathNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选器表达式不能为空 的本地化字符串。
        /// </summary>
        internal static string exception_FilterCannotBeNull {
            get {
                return ResourceManager.GetString("exception_FilterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包括路径不能是null或空字符串 的本地化字符串。
        /// </summary>
        internal static string exception_IncludePathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("exception_IncludePathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageIndex * PageCount产生溢出异常 的本地化字符串。
        /// </summary>
        internal static string exception_InvalidElementsInPage {
            get {
                return ResourceManager.GetString("exception_InvalidElementsInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageCount小于零 的本地化字符串。
        /// </summary>
        internal static string exception_InvalidPageCount {
            get {
                return ResourceManager.GetString("exception_InvalidPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageIndex小于零 的本地化字符串。
        /// </summary>
        internal static string exception_InvalidPageIndex {
            get {
                return ResourceManager.GetString("exception_InvalidPageIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 为空 的本地化字符串。
        /// </summary>
        internal static string exception_ItemArgumentIsNull {
            get {
                return ResourceManager.GetString("exception_ItemArgumentIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序表达式不能为空 的本地化字符串。
        /// </summary>
        internal static string exception_OrderByExpressionCannotBeNull {
            get {
                return ResourceManager.GetString("exception_OrderByExpressionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specification cannot be null 的本地化字符串。
        /// </summary>
        internal static string exception_SpecificationIsNull {
            get {
                return ResourceManager.GetString("exception_SpecificationIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trace manager cannot be null 的本地化字符串。
        /// </summary>
        internal static string exception_TraceManagerCannotBeNull {
            get {
                return ResourceManager.GetString("exception_TraceManagerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added object of type {0} in repository 的本地化字符串。
        /// </summary>
        internal static string trace_AddedItemRepository {
            get {
                return ResourceManager.GetString("trace_AddedItemRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applied changes of type {0} in repository 的本地化字符串。
        /// </summary>
        internal static string trace_AppliedChangedItemRepository {
            get {
                return ResourceManager.GetString("trace_AppliedChangedItemRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attached item in repository of type {0} 的本地化字符串。
        /// </summary>
        internal static string trace_AttachedItemToRepository {
            get {
                return ResourceManager.GetString("trace_AttachedItemToRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created repository for type {0} 的本地化字符串。
        /// </summary>
        internal static string trace_ConstructRepository {
            get {
                return ResourceManager.GetString("trace_ConstructRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted object of type {0} in repository 的本地化字符串。
        /// </summary>
        internal static string trace_DeletedItemRepository {
            get {
                return ResourceManager.GetString("trace_DeletedItemRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetAll called in repository of type {0} 的本地化字符串。
        /// </summary>
        internal static string trace_GetAllRepository {
            get {
                return ResourceManager.GetString("trace_GetAllRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get items by specification in repository of type {0} 的本地化字符串。
        /// </summary>
        internal static string trace_GetBySpec {
            get {
                return ResourceManager.GetString("trace_GetBySpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetFilteredElements called in repository of type {0} with Filter:{1} 的本地化字符串。
        /// </summary>
        internal static string trace_GetFilteredElementsRepository {
            get {
                return ResourceManager.GetString("trace_GetFilteredElementsRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetFilteredElements called in repository of type {0} with Filter:{1} PageIndex:{2} PageCount:{3} OrderBy:{4} 的本地化字符串。
        /// </summary>
        internal static string trace_GetFilteredPagedElementsRepository {
            get {
                return ResourceManager.GetString("trace_GetFilteredPagedElementsRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GetPagedElements called in repository of type {0} with PageIndex:{1},PageCount:{2},OrderBy:{3} 的本地化字符串。
        /// </summary>
        internal static string trace_GetPagedElementsRepository {
            get {
                return ResourceManager.GetString("trace_GetPagedElementsRepository", resourceCulture);
            }
        }
    }
}
