//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

#pragma warning disable 1591 // this is for supress no xml comments in public members warnings 

using Domain.Core.Entities;

namespace Domain.ExpressModule.Entities
{
    [DataContract(IsReference = true)]
    [System.CodeDom.Compiler.GeneratedCode("STE-EF",".NET 4.0")]
    #if !SILVERLIGHT
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage()]
    #endif
    public partial class OrderInfo: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private int _id;
    
        [DataMember]
        public string UniqueId
        {
            get { return _uniqueId; }
            set
            {
                if (_uniqueId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'UniqueId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _uniqueId = value;
                    OnPropertyChanged("UniqueId");
                }
            }
        }
        private string _uniqueId;
    
        [DataMember]
        public string Csr_UniqueId_J
        {
            get { return _csr_UniqueId_J; }
            set
            {
                if (_csr_UniqueId_J != value)
                {
                    _csr_UniqueId_J = value;
                    OnPropertyChanged("Csr_UniqueId_J");
                }
            }
        }
        private string _csr_UniqueId_J;
    
        [DataMember]
        public string Csr_Name_J
        {
            get { return _csr_Name_J; }
            set
            {
                if (_csr_Name_J != value)
                {
                    _csr_Name_J = value;
                    OnPropertyChanged("Csr_Name_J");
                }
            }
        }
        private string _csr_Name_J;
    
        [DataMember]
        public string Csr_Tel_J
        {
            get { return _csr_Tel_J; }
            set
            {
                if (_csr_Tel_J != value)
                {
                    _csr_Tel_J = value;
                    OnPropertyChanged("Csr_Tel_J");
                }
            }
        }
        private string _csr_Tel_J;
    
        [DataMember]
        public string Csr_Addr_J
        {
            get { return _csr_Addr_J; }
            set
            {
                if (_csr_Addr_J != value)
                {
                    _csr_Addr_J = value;
                    OnPropertyChanged("Csr_Addr_J");
                }
            }
        }
        private string _csr_Addr_J;
    
        [DataMember]
        public string Csr_AddrDetail_J
        {
            get { return _csr_AddrDetail_J; }
            set
            {
                if (_csr_AddrDetail_J != value)
                {
                    _csr_AddrDetail_J = value;
                    OnPropertyChanged("Csr_AddrDetail_J");
                }
            }
        }
        private string _csr_AddrDetail_J;
    
        [DataMember]
        public string Csr_PostCode_J
        {
            get { return _csr_PostCode_J; }
            set
            {
                if (_csr_PostCode_J != value)
                {
                    _csr_PostCode_J = value;
                    OnPropertyChanged("Csr_PostCode_J");
                }
            }
        }
        private string _csr_PostCode_J;
    
        [DataMember]
        public string Csr_UniqueId_S
        {
            get { return _csr_UniqueId_S; }
            set
            {
                if (_csr_UniqueId_S != value)
                {
                    _csr_UniqueId_S = value;
                    OnPropertyChanged("Csr_UniqueId_S");
                }
            }
        }
        private string _csr_UniqueId_S;
    
        [DataMember]
        public string Csr_Name_S
        {
            get { return _csr_Name_S; }
            set
            {
                if (_csr_Name_S != value)
                {
                    _csr_Name_S = value;
                    OnPropertyChanged("Csr_Name_S");
                }
            }
        }
        private string _csr_Name_S;
    
        [DataMember]
        public string Csr_Tel_S
        {
            get { return _csr_Tel_S; }
            set
            {
                if (_csr_Tel_S != value)
                {
                    _csr_Tel_S = value;
                    OnPropertyChanged("Csr_Tel_S");
                }
            }
        }
        private string _csr_Tel_S;
    
        [DataMember]
        public string Csr_Addr_S
        {
            get { return _csr_Addr_S; }
            set
            {
                if (_csr_Addr_S != value)
                {
                    _csr_Addr_S = value;
                    OnPropertyChanged("Csr_Addr_S");
                }
            }
        }
        private string _csr_Addr_S;
    
        [DataMember]
        public string Csr_AddrDetail_S
        {
            get { return _csr_AddrDetail_S; }
            set
            {
                if (_csr_AddrDetail_S != value)
                {
                    _csr_AddrDetail_S = value;
                    OnPropertyChanged("Csr_AddrDetail_S");
                }
            }
        }
        private string _csr_AddrDetail_S;
    
        [DataMember]
        public Nullable<System.DateTime> ExpectTime
        {
            get { return _expectTime; }
            set
            {
                if (_expectTime != value)
                {
                    _expectTime = value;
                    OnPropertyChanged("ExpectTime");
                }
            }
        }
        private Nullable<System.DateTime> _expectTime;
    
        [DataMember]
        public string Goods
        {
            get { return _goods; }
            set
            {
                if (_goods != value)
                {
                    _goods = value;
                    OnPropertyChanged("Goods");
                }
            }
        }
        private string _goods;
    
        [DataMember]
        public Nullable<double> ExpectWeight
        {
            get { return _expectWeight; }
            set
            {
                if (_expectWeight != value)
                {
                    _expectWeight = value;
                    OnPropertyChanged("ExpectWeight");
                }
            }
        }
        private Nullable<double> _expectWeight;
    
        [DataMember]
        public Nullable<double> SupportPrice
        {
            get { return _supportPrice; }
            set
            {
                if (_supportPrice != value)
                {
                    _supportPrice = value;
                    OnPropertyChanged("SupportPrice");
                }
            }
        }
        private Nullable<double> _supportPrice;
    
        [DataMember]
        public string Payway
        {
            get { return _payway; }
            set
            {
                if (_payway != value)
                {
                    _payway = value;
                    OnPropertyChanged("Payway");
                }
            }
        }
        private string _payway;
    
        [DataMember]
        public Nullable<double> ExpectPrice
        {
            get { return _expectPrice; }
            set
            {
                if (_expectPrice != value)
                {
                    _expectPrice = value;
                    OnPropertyChanged("ExpectPrice");
                }
            }
        }
        private Nullable<double> _expectPrice;
    
        [DataMember]
        public Nullable<double> Weight
        {
            get { return _weight; }
            set
            {
                if (_weight != value)
                {
                    _weight = value;
                    OnPropertyChanged("Weight");
                }
            }
        }
        private Nullable<double> _weight;
    
        [DataMember]
        public string Operatior
        {
            get { return _operatior; }
            set
            {
                if (_operatior != value)
                {
                    _operatior = value;
                    OnPropertyChanged("Operatior");
                }
            }
        }
        private string _operatior;
    
        [DataMember]
        public Nullable<System.DateTime> ReceiptTime
        {
            get { return _receiptTime; }
            set
            {
                if (_receiptTime != value)
                {
                    _receiptTime = value;
                    OnPropertyChanged("ReceiptTime");
                }
            }
        }
        private Nullable<System.DateTime> _receiptTime;
    
        [DataMember]
        public Nullable<int> Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private Nullable<int> _status;
    
        [DataMember]
        public string Mark
        {
            get { return _mark; }
            set
            {
                if (_mark != value)
                {
                    _mark = value;
                    OnPropertyChanged("Mark");
                }
            }
        }
        private string _mark;
    
        [DataMember]
        public string StatusMark
        {
            get { return _statusMark; }
            set
            {
                if (_statusMark != value)
                {
                    _statusMark = value;
                    OnPropertyChanged("StatusMark");
                }
            }
        }
        private string _statusMark;
    
        [DataMember]
        public string WaybillNo
        {
            get { return _waybillNo; }
            set
            {
                if (_waybillNo != value)
                {
                    _waybillNo = value;
                    OnPropertyChanged("WaybillNo");
                }
            }
        }
        private string _waybillNo;
    
        [DataMember]
        public Nullable<System.DateTime> CreateTime
        {
            get { return _createTime; }
            set
            {
                if (_createTime != value)
                {
                    _createTime = value;
                    OnPropertyChanged("CreateTime");
                }
            }
        }
        private Nullable<System.DateTime> _createTime;
    
        [DataMember]
        public string Csr_PostCode_S
        {
            get { return _csr_PostCode_S; }
            set
            {
                if (_csr_PostCode_S != value)
                {
                    _csr_PostCode_S = value;
                    OnPropertyChanged("Csr_PostCode_S");
                }
            }
        }
        private string _csr_PostCode_S;
    
        [DataMember]
        public string WechatId
        {
            get { return _wechatId; }
            set
            {
                if (_wechatId != value)
                {
                    _wechatId = value;
                    OnPropertyChanged("WechatId");
                }
            }
        }
        private string _wechatId;
    
        [DataMember]
        public Nullable<System.DateTime> CancelTime
        {
            get { return _cancelTime; }
            set
            {
                if (_cancelTime != value)
                {
                    _cancelTime = value;
                    OnPropertyChanged("CancelTime");
                }
            }
        }
        private Nullable<System.DateTime> _cancelTime;
    
        [DataMember]
        public Nullable<System.DateTime> PayTime
        {
            get { return _payTime; }
            set
            {
                if (_payTime != value)
                {
                    _payTime = value;
                    OnPropertyChanged("PayTime");
                }
            }
        }
        private Nullable<System.DateTime> _payTime;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
